import type { Metadata } from 'next';
import './globals.css';
import { SidebarProvider } from '@seoul-rebels/ui';
import { AdminSidebar } from '@/components/AdminSidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`min-h-dvh antialiased`}>
      <body className="min-h-full flex flex-col bg-brand-accent-200">
        <SidebarProvider>
          <AdminSidebar />
          <main>{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
