import type { Metadata } from 'next';
import './globals.css';
import { SidebarProvider, ThemeProvider, Toaster } from '@seoul-rebels/ui';
import { AdminSidebar } from '@/components/AdminSidebar';
import { QueryProvider } from '@/components/QueryProvider';
import AdminNav from '@/components/AdminNav';

export const metadata: Metadata = {
  title: {
    default: 'Seoul Rebels',
    template: '%s | Seoul Rebels',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`min-h-dvh antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full bg-brand-accent-50">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AdminSidebar />
            <QueryProvider>
              <main className="w-full">
                <AdminNav />
                {children}
                <Toaster richColors closeButton position="bottom-center" />
              </main>
            </QueryProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
