/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type ProductVariantReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productVariant';
};

export type ShopTheLook = {
  _id: string;
  _type: 'shopTheLook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  body?: LocaleText;
  products?: Array<{
    variant?: ProductVariantReference;
    positionXPercent?: number;
    positionYPercent?: number;
    _type: 'product';
    _key: string;
  }>;
  mainImage?: ImageWithAlt;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type ImageWithAlt = {
  _type: 'imageWithAlt';
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type LocaleText = {
  _type: 'localeText';
  en?: string;
  ko?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Lookbook = {
  _id: string;
  _type: 'lookbook';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  slug?: Slug;
  mainImage?: ImageWithAlt;
  products?: Array<
    {
      _key: string;
    } & ProductVariantReference
  >;
};

export type LocaleString = {
  _type: 'localeString';
  en?: string;
  ko?: string;
};

export type Collection = {
  _id: string;
  _type: 'collection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  slug?: Slug;
  mainImage?: ImageWithAlt;
  products?: Array<
    {
      _key: string;
    } & ProductVariantReference
  >;
};

export type SizeChart = {
  _id: string;
  _type: 'sizeChart';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: ImageWithAlt;
  sizeDesc?: Array<{
    label?: LocaleString;
    body?: LocaleText;
    _key: string;
  }>;
  sizes?: Array<{
    label?: string;
    measurements?: Array<
      {
        _key: string;
      } & Measurement
    >;
    _type: 'size';
    _key: string;
  }>;
};

export type ProductVariant = {
  _id: string;
  _type: 'productVariant';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  sku?: string;
  priceInUSD?: number;
  priceInKRW?: number;
  size?: 'xs' | 's' | 'm' | 'l' | 'xl';
  color?: Color;
  mainImages?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
};

export type Color = {
  _type: 'color';
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type BrandReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'brand';
};

export type ProductCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productCategory';
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  brand?: BrandReference;
  category?: ProductCategoryReference;
  body?: LocaleContent;
  variants?: Array<
    {
      _key: string;
    } & ProductVariantReference
  >;
};

export type LocaleContent = {
  _type: 'localeContent';
  en?: BlockContent;
  ko?: BlockContent;
};

export type ProductCategory = {
  _id: string;
  _type: 'productCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  slug?: Slug;
  mainImage?: ImageWithAlt;
};

export type Brand = {
  _id: string;
  _type: 'brand';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: ImageWithAlt;
};

export type DepartmentReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'department';
};

export type JobOffer = {
  _id: string;
  _type: 'jobOffer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  department?: DepartmentReference;
  body?: LocaleContent;
  openedDate?: string;
  closedDate?: string;
};

export type Department = {
  _id: string;
  _type: 'department';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type BlogCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogCategory';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  author?: AuthorReference;
  category?: BlogCategoryReference;
  publishedAt?: string;
  minRead?: number;
  mainImage?: ImageWithAlt;
  seo?: Seo;
  excerpt?: LocaleText;
  body?: LocaleContent;
  isMemberOnly?: boolean;
  isFeatured?: boolean;
};

export type Seo = {
  _type: 'seo';
  metaTitle?: LocaleString;
  metaDescription?: LocaleText;
  ogImage?: ImageWithAlt;
  noIndex?: boolean;
};

export type BlogCategory = {
  _id: string;
  _type: 'blogCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  slug?: Slug;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  bio?: LocaleText;
  specializeIn?: LocaleString;
  mainImage?: ImageWithAlt;
  socialLink?: SocialLink;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?:
    'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'twitter-x' | 'github';
  url?: string;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  position?: string;
  mainImage?: ImageWithAlt;
};

export type Stockist = {
  _id: string;
  _type: 'stockist';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  contacts?: ContactInfo;
  storeHours?: Array<{
    day?: number;
    openingHours?: string;
    closingHours?: string;
    _type: 'storeHour';
    _key: string;
  }>;
  mainImage?: ImageWithAlt;
};

export type ContactInfo = {
  _type: 'contactInfo';
  email?: string;
  phone?: string;
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
};

export type Faqs = {
  _id: string;
  _type: 'faqs';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  slug?: Slug;
  contents?: Faq;
};

export type Faq = {
  _type: 'faq';
  title?: LocaleString;
  body?: LocaleText;
};

export type Milestone = {
  _id: string;
  _type: 'milestone';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slogan?: LocaleString;
  slug?: Slug;
  year?: number;
  body?: LocaleText;
};

export type UtilityPage = {
  _id: string;
  _type: 'utilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  seo?: Seo;
  body?: LocaleContent;
};

export type Hero = {
  _id: string;
  _type: 'hero';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  banners?: Array<
    | ({
        _key: string;
      } & LocaleString)
    | ({
        _key: string;
      } & LocaleText)
    | ({
        _key: string;
      } & ImageWithAlt)
  >;
};

export type Measurement = {
  _type: 'measurement';
  label?:
    | 'shoulder'
    | 'chest'
    | 'length'
    | 'sleeve'
    | 'waist'
    | 'hips'
    | 'inseam'
    | 'rise';
  value?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type RgbaColor = {
  _type: 'rgbaColor';
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: 'hsvaColor';
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: 'hslaColor';
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductVariantReference
  | ShopTheLook
  | SanityImageAssetReference
  | ImageWithAlt
  | LocaleText
  | Slug
  | Lookbook
  | LocaleString
  | Collection
  | SizeChart
  | ProductVariant
  | Color
  | BrandReference
  | ProductCategoryReference
  | Product
  | LocaleContent
  | ProductCategory
  | Brand
  | DepartmentReference
  | JobOffer
  | Department
  | AuthorReference
  | BlogCategoryReference
  | Blog
  | Seo
  | BlogCategory
  | Author
  | SocialLink
  | TeamMember
  | Stockist
  | ContactInfo
  | Faqs
  | Faq
  | Milestone
  | UtilityPage
  | Hero
  | Measurement
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/query.ts
// Variable: ALL_STOCKISTS
// Query: *[_type == 'stockist' && defined(slug.current) ]| order(_createdAt){  _id,  name,  "slug": slug.current,  "imageUrl": mainImage.asset->url,  "imageAlt": mainImage.alt,  "city": contacts.city,  "country": contacts.country }
export type ALL_STOCKISTS_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  city: string | null;
  country: string | null;
}>;

// Source: src/sanity/query.ts
// Variable: STOCKIST
// Query: *[_type == 'stockist' && slug.current == $slug ][0]{  _id,    name,  "slug": slug.current,  "imageUrl": mainImage.asset->url,  "imageAlt": mainImage.alt,  contacts,  storeHours[],  "imageAssetId": mainImage.asset._ref, }
export type STOCKIST_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  contacts: ContactInfo | null;
  storeHours: Array<{
    day?: number;
    openingHours?: string;
    closingHours?: string;
    _type: 'storeHour';
    _key: string;
  }> | null;
  imageAssetId: string | null;
} | null;

// Source: src/sanity/query.ts
// Variable: ALL_TEAMMEMBERS
// Query: *[_type == 'teamMember' && defined(slug.current)]  |order($order)  {  _id,  name,  "slug": slug.current,  position,  "imageUrl": mainImage.asset->url,  "imageAlt": mainImage.alt }
export type ALL_TEAMMEMBERS_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  position: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
}>;

// Source: src/sanity/query.ts
// Variable: TEAMMEMBER
// Query: *[_type == 'teamMember' && slug.current == $slug][0]  {  _id,  name,  "slug": slug.current,  position,  "imageUrl": mainImage.asset->url,  "imageAlt": mainImage.alt,  "imageAssetId": mainImage.asset._ref }
export type TEAMMEMBER_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  position: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
  imageAssetId: string | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == \'stockist\'\n && defined(slug.current)\n ]| order(_createdAt){\n  _id,\n  name,\n  "slug": slug.current,\n  "imageUrl": mainImage.asset->url,\n  "imageAlt": mainImage.alt,\n  "city": contacts.city,\n  "country": contacts.country\n }\n': ALL_STOCKISTS_RESULT;
    '*[_type == \'stockist\'\n && slug.current == $slug\n ][0]{\n  _id,  \n  name,\n  "slug": slug.current,\n  "imageUrl": mainImage.asset->url,\n  "imageAlt": mainImage.alt,\n  contacts,\n  storeHours[],\n  "imageAssetId": mainImage.asset._ref,\n }\n': STOCKIST_RESULT;
    '*[_type == \'teamMember\'\n && defined(slug.current)]\n  |order($order)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  position,\n  "imageUrl": mainImage.asset->url,\n  "imageAlt": mainImage.alt\n }': ALL_TEAMMEMBERS_RESULT;
    '*[_type == \'teamMember\'\n && slug.current == $slug][0]\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  position,\n  "imageUrl": mainImage.asset->url,\n  "imageAlt": mainImage.alt,\n  "imageAssetId": mainImage.asset._ref\n }': TEAMMEMBER_RESULT;
  }
}
